### ISSUE TITLE
<Super> key not being captured when trying to input a new shortcut

### ISSUE THREAD

**Issue by rivenirvana** [christopher-l/space-bar#14] opened 2023-07-23 12:01 UTC

**Comment by christopher-l** [comment] 2023-08-05 16:58
@rivenirvana thanks for your report.

Which version of GNOME are you using, which distribution, and are you on X11 or Wayland?

Also, could you run the following command while trying to assign a shortcut and see if anything pops up?
```sh
journalctl -f -o cat /usr/bin/gjs
```

**Comment by christopher-l** [comment] 2023-09-03 13:49
Did you find anything yet?

Since I am not able to reproduce this, I will close the issue soon, otherwise.

**Closed** 2023-11-05 11:07 UTC
